Add origin trial graduation information to AudioWorklet
jpchase/ExperimentalFramework pull request #39
Opened 2018-03-14 11:54 UTC by jpmedley

Because we can use this page to direct people to newer resources when they become available. I'll update this again when I have some links. We should keep this here for a few cycles.

2018-03-23 16:04 UTC, jpmedley commented
@jpchase

2018-03-23 17:24 UTC, jpchase commented on available-trials.md
> +| [AudioWorklet](https://webaudio.github.io/web-audio-api/#AudioWorklet) | The AudioWorklet exposes the low-level audio processing capability to web developers within Web Audio API's ecosystem. It st
Typically, this list uses "First available in ..." to note the release in which the origin trial starts. 

The addition about "available with origin trial in Chrome 66" is actually incorrect. The origin trial only runs through 65 (the integration was removed for 66). What is the intent there?

I can see the benefit in adding graduation info before the trials ends. I think is confusing as stated. How about adding a single statement like "Shipping in Chrome M66, beta available March 15, 2018". I find that clearer, and similar to the format on the completed trials list.

2018-03-23 18:27 UTC, jpmedley commented on available-trials.md
> +| [AudioWorklet](https://webaudio.github.io/web-audio-api/#AudioWorklet) | The AudioWorklet exposes the low-level audio processing capability to web developers within Web Audio API's ecosystem. It st
'Available with origin trial in Chrome 66'. I don't think that's what I meant to type.

2018-03-23 18:28 UTC, jpmedley commented
PTAL.

2018-03-27 17:36 UTC, jpmedley commented
Ping!

2018-03-28 13:35 UTC, clelland requested changes

2018-03-28 13:35 UTC, clelland commented on available-trials.md
> +| [AudioWorklet](https://webaudio.github.io/web-audio-api/#AudioWorklet) | The AudioWorklet exposes the low-level audio processing capability to web developers within Web Audio API's ecosystem. It st
We should probably be consistent with the version naming within this file (Chrome 64 vs Chrome M64) -- otherwise, this looks good.

2018-03-29 19:30 UTC, clelland approved these changes

2018-03-29 19:31 UTC, merged